version: "3"
services:
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
            - ../..:/data  
        environment:
            MYSQL_ROOT_PASSWORD: root_pwd
            MYSQL_DATABASE: db_chatbot
            MYSQL_USER: db_chatbot
            MYSQL_PASSWORD: db_chatbot_pwd
    chatbot:
        tty: true
        build: .
        ports:
            - 3001:3001
        volumes:
            - ../..:/home/chatbot
    nginx:
        image: "nginx:1.13.5"
        ports:
            - "80:80"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        links:
            - chatbot
        depends_on: 
            - chatbot
volumes:
  app:
  db-data:
    driver: local
