version: "3"
services:
    db_chatbot:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
            - .:/data  
        environment:
            MYSQL_ROOT_PASSWORD: root_pwd
            MYSQL_DATABASE: db_chatbot
            MYSQL_USER: db_chatbot
            MYSQL_PASSWORD: db_chatbot_pwd

volumes:
  app:
  db-data:
    driver: local
