version: "3"
services:
    db:
        image: mysql:5.7
        ports:
            - 3308:3306
        volumes:
            - db-data:/var/lib/mysql
            - ..:/data  
        environment:
            MYSQL_ROOT_PASSWORD: root_pwd
            MYSQL_DATABASE: db_chatbot
            MYSQL_USER: db_chatbot
            MYSQL_PASSWORD: db_chatbot_pwd
    chatbot:
        tty: true
        build: ./web
        environment:
            TZ: Europe/Paris
        volumes:
            - ..:/home/chatbot
    nginx:
        build: ./nginx
        ports:
            - "81:80"
        depends_on: 
            - chatbot
volumes:
  app:
  db-data:
    driver: local
